### ISSUE TITLE
Potential improvement: add ICS Edition 6

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/iso-ics-codes#3]
Some organizations are still using ICS Edition 6, which is uploaded here.
[ICS_ISO_Ed_6_2005_en.pdf](https://github.com/metanorma/iso-ics-codes/files/9429005/ICS_ISO_Ed_6_2005_en.pdf)

**Comment by ronaldtse** [comment]
Cleaned up codes into Excel:
[2005-iso-ics-edition-6.xlsx](https://github.com/metanorma/iso-ics-codes/files/9429256/2005-iso-ics-edition-6.xlsx)

**Comment by ronaldtse** [comment]
We should encode this in YAML-LD, it would look like this:

Corresonding JSON-LD:
https://github.com/metanorma/iso-ics-codes/blob/c82f544cbe5173a1423bc9cc65464ce01e85e73a/ics/01_040_01.json#L1-L9

Sample encodings from Excel/PDF:

## ICS Field

<img width="402" alt="Screen Shot 2022-08-26 at 3 14 31 PM" src="https://user-images.githubusercontent.com/11865/186844602-7b20fa4c-cd37-45da-a2a5-f28f46db052a.png">

`01.yaml`
```yaml
%YAML 1.2
---
"@context": https://isoics.org/ics/ns/field.yamlld
edition: 6
code: "01"
fieldcode: "01"
description: Generalities. Terminology. Standardization. Documentation.
```

<img width="416" alt="Screen Shot 2022-08-26 at 3 14 20 PM" src="https://user-images.githubusercontent.com/11865/186844559-25a01ee1-37e6-4c8d-90e1-b06e09ea7850.png">

## ICS Group

`01_040.yaml`
```yaml
%YAML 1.2
---
"@context": https://isoics.org/ics/ns/group.yamlld
edition: 6
code: "01.040"
fieldcode: "01"
groupcode: "040"
description: Vocabularies
descriptionFull: |
  Generalities. Terminology. Standardization. Documentation. Vocabularies.
notes: 
  - text: |
    Standards included in this group shall also be included in other groups
    and/or sub-groups according to their subject
```

## ICS Subgroup

<img width="392" alt="Screen Shot 2022-08-26 at 3 10 14 PM" src="https://user-images.githubusercontent.com/11865/186843859-22a57275-e7d8-4892-9e02-db10f1d1de8e.png">

`01_040_01.yaml`
```yaml
%YAML 1.2
---
"@context": https://isoics.org/ics/ns/subgroup.yamlld
edition: 6
code: "01.040.01"
fieldcode: "01"
description: Generalities. Terminology. Standardization. Documentation (Vocabularies)
groupcode: "040"
subgroupcode: "01"
descriptionFull: |
  Generalities. Terminology. Standardization. Documentation (Vocabularies)
```

## Referencing other ICS codes in notes

For some entries that have a "see {...}" which refers to another ICS code, we do the following:
https://github.com/metanorma/iso-ics-codes/blob/8ba0ae1577cedb192d7658f9933a7c769e5a4bdf/ics/01_100.json#L1-L18

<img width="426" alt="Screen Shot 2022-08-26 at 3 17 23 PM" src="https://user-images.githubusercontent.com/11865/186845043-72748bad-a89a-47ee-aeb2-3cc0db74bfc1.png">

`01_100.yaml`
```yaml
%YAML 1.2
---
"@context": https://isoics.org/ics/ns/group.yamlld
edition: 6
code: "01.100"
fieldcode: "01"
groupcode: "040"
description: Technical drawings
descriptionFull: |
  Generalities. Terminology. Standardization. Documentation. Technical drawings.
notes: 
  - text: Graphical symbols for use on technical drawings, see {ics-code}
    ics-code: "01.080.30"
  - text: Computer-aided design, see {ics-code}
    ics-code: "35.240.10"
```
